"""
NOTE: these tests require the MockBank mock app to be running on http://localhost:5050
(python mock_app/app.py) - the replay engine drives a real browser against it.

They use artifacts/search_for_member_10001_open_a_sub_account_v1.json, the artifact
auto-generated by agent/build_artifact.py from a real discovery run. Unlike the
hand-written artifacts/open_sub_account_v1.json example, this one includes the login
steps MockBank actually requires before /search, /member, etc. become reachable, so
it can be replayed standalone from a fresh browser session.
"""

import json
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "replay"))

from engine import replay  # noqa: E402
from safety.guardrails import is_risky_step  # noqa: E402
from schemas.artifact_schema import CapabilityArtifact  # noqa: E402

BASE_URL = "http://localhost:5050"
ARTIFACT_PATH = PROJECT_ROOT / "artifacts" / "search_for_member_10001_open_a_sub_account_v1.json"

pytestmark = pytest.mark.skipif(
    not ARTIFACT_PATH.exists(),
    reason=f"required artifact not found: {ARTIFACT_PATH}",
)


def _base_inputs(**overrides) -> dict:
    inputs = {
        "username": "tester",
        "password": "pw",
        "member_id": "10002",
        "account_type": "Checking",
        "initial_deposit": 100,
    }
    inputs.update(overrides)
    return inputs


def test_successful_replay_with_different_member():
    result = replay(
        str(ARTIFACT_PATH),
        _base_inputs(member_id="10003", account_type="Savings", confirmed=True),
        BASE_URL,
    )

    assert result["status"] == "success"
    assert "reference_number" in result["outputs"]
    assert result["outputs"]["reference_number"].startswith("REF-")
    assert result["steps_completed"] > 0


def test_business_outcome_for_nonexistent_member():
    result = replay(str(ARTIFACT_PATH), _base_inputs(member_id="99999"), BASE_URL)

    assert result["status"] == "business_outcome"
    assert result["outcome"] == "member_not_found"


def test_invalid_deposit_is_rejected_before_opening_a_browser():
    result = replay(str(ARTIFACT_PATH), _base_inputs(initial_deposit=-10), BASE_URL)

    assert result["status"] == "invalid_input"
    assert any("initial_deposit" in err for err in result["errors"])


def test_replay_without_confirmation_stops_before_submit():
    # No "confirmed" key at all - the risky Submit step must not be performed.
    result = replay(str(ARTIFACT_PATH), _base_inputs(), BASE_URL)

    assert result["status"] == "requires_confirmation"
    assert "message" in result

    artifact = CapabilityArtifact.load(ARTIFACT_PATH)
    risky_step_ids = {step.step_id for step in artifact.steps if is_risky_step(step)}
    final_step_id = artifact.steps[-1].step_id

    assert result["step"] in risky_step_ids
    assert result["step"] < final_step_id

    # Confirm the confirmation page was never reached: the final verify_checkpoint
    # step never appears in the executed step log at all, so no sub-account was created.
    log_data = json.loads((Path(result["evidence_dir"]) / "log.json").read_text())
    executed_step_ids = [entry["step_id"] for entry in log_data["steps"]]
    assert final_step_id not in executed_step_ids


def test_replay_with_confirmation_proceeds_and_succeeds():
    # Same setup as the successful-replay case, with confirmed=True added.
    result = replay(
        str(ARTIFACT_PATH),
        _base_inputs(member_id="10003", account_type="Savings", confirmed=True),
        BASE_URL,
    )

    assert result["status"] == "success"
    assert "reference_number" in result["outputs"]
    assert result["outputs"]["reference_number"].startswith("REF-")
